version: '3.1'

services:
  api:
    build: 
      context: .
    container_name: api-latency
    ports:
      - 6500:8000
    environment:
      - PORT=8000
      - FILEPATH=files
    volumes:
      - .:/app-vol
    restart: 
      on-failure


      
